Swtiched intake to use one talon
Yeti-Robotics/charged-up-java-2023 pull request #32
Opened 2023-03-23 22:56 UTC by VGopal06

2023-03-23 23:21 UTC, Amehta996 commented on src/main/java/frc/robot/constants/IntakeConstants.java
>      public static final int RIGHT_SPARK_ID = 2;
1. Rename it from intake spark 1 to just intake falcon
2. Remove the Right Spark
3. Change the `Left_Spark_ID` to Intake Falcon ID and set it to 1
4. Remove `RIGHT_SPARK_ID.

2023-03-23 23:22 UTC, Amehta996 commented on src/main/java/frc/robot/di/devices/MotorsModule.java
> +        talon.setInverted(false);
1. Add CanBus frame timings

2023-03-23 23:23 UTC, Amehta996 commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
> +    private final WPI_TalonFX talon;
refactor talon to intakeMotor

2023-03-23 23:23 UTC, Amehta996 requested changes
Look at comments made

2023-03-24 15:56 UTC, vwu1888 approved these changes
lgtm

2023-03-24 15:57 UTC, merged